# Generated by Django 3.1.4 on 2020-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
                'ordering': ['-published'],
            },
        ),
        migrations.DeleteModel(
            name='MyTestModel',
        ),
    ]
