# Generated by Django 3.1.4 on 2020-12-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201203_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={},
        ),
    ]
