# Generated by Django 3.1.7 on 2021-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hours',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Количество рабочих часов'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rate',
            field=models.FloatField(default=None, null=True, verbose_name='Ставка'),
        ),
    ]
