# Generated by Django 3.1.7 on 2021-03-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201220_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chair',
            options={'ordering': ['name'], 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='class_schedule',
            options={'ordering': ['room'], 'verbose_name': 'Расписание аудитории', 'verbose_name_plural': 'Расписания аудиторий'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['name'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='exam_schedule',
            options={'ordering': ['name'], 'verbose_name': 'Подгруппа', 'verbose_name_plural': 'Подгруппы'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Аудитория', 'verbose_name_plural': 'Аудитории'},
        ),
        migrations.AlterModelOptions(
            name='subgroup',
            options={'verbose_name': 'Подгруппа', 'verbose_name_plural': 'Подгруппы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='work_time',
            options={'verbose_name': 'Рабочее время', 'verbose_name_plural': 'Рабочее время'},
        ),
        migrations.AlterField(
            model_name='chair',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.chair', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Код направления'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='qualification',
            field=models.CharField(max_length=63, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='date',
            field=models.DateField(verbose_name='Дата экзамена'),
        ),
        migrations.AlterField(
            model_name='exam_schedule',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='amount',
            field=models.PositiveIntegerField(max_length=3, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='amount',
            field=models.PositiveIntegerField(max_length=3, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='group_parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group', verbose_name='Родительская группа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.chair', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=31, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=31, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=31, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.work_time', verbose_name='Рабочее время'),
        ),
    ]
