# Generated by Django 3.1.7 on 2021-03-10 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210310_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='discipline_name',
            field=models.CharField(max_length=63, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='class_schedule',
            name='end_time',
            field=models.DateTimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='class_schedule',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='class_schedule',
            name='periodicity',
            field=models.CharField(max_length=3, verbose_name='Частота'),
        ),
        migrations.AlterField(
            model_name='class_schedule',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.room', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='class_schedule',
            name='start_time',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='class_schedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='class_schedule',
            name='week_day',
            field=models.DateField(verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Емкость'),
        ),
        migrations.AlterField(
            model_name='room',
            name='corps_index',
            field=models.CharField(max_length=7, verbose_name='Индекс корпуса'),
        ),
        migrations.AlterField(
            model_name='room',
            name='corps_number',
            field=models.PositiveIntegerField(verbose_name='Номер корпуса'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_room',
            field=models.CharField(max_length=31, verbose_name='Тип аудитории'),
        ),
    ]
