# Generated by Django 3.1.7 on 2021-03-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210310_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_schedule',
            options={'ordering': ['room'], 'verbose_name': 'Расписание занятия', 'verbose_name_plural': 'Расписание занятий'},
        ),
    ]
