# Generated by Django 3.1.7 on 2021-03-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210311_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_time',
            name='friday',
            field=models.CharField(default='Нет', max_length=3, verbose_name='Пятница'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='monday',
            field=models.CharField(default='Нет', max_length=3, verbose_name='Понедельник'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='saturday',
            field=models.CharField(default='Нет', max_length=3, verbose_name='Суббота'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='thursday',
            field=models.CharField(default='Нет', max_length=3, verbose_name='Четвер'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='wednesday',
            field=models.CharField(default='Нет', max_length=3, verbose_name='Среда'),
        ),
    ]
