# Generated by Django 3.1.7 on 2021-03-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210311_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_time',
            options={'verbose_name': 'Рабочее время преподавателей', 'verbose_name_plural': 'Рабочее время преподавателя'},
        ),
        migrations.RemoveField(
            model_name='work_time',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='work_time',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='work_time',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='work_time',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='work_time',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='work_time',
            name='friday_end',
            field=models.TimeField(null=True, verbose_name='Пятница - конец'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='friday_start',
            field=models.TimeField(null=True, verbose_name='Пятница - начало'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='monday_end',
            field=models.TimeField(null=True, verbose_name='Понедельник - конец'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='monday_start',
            field=models.TimeField(null=True, verbose_name='Понедельник - начало'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='saturday_end',
            field=models.TimeField(null=True, verbose_name='Суббота - конец'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='saturday_start',
            field=models.TimeField(null=True, verbose_name='Суббота - начало'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='thursday_end',
            field=models.TimeField(null=True, verbose_name='Четверг - конец'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='thursday_start',
            field=models.TimeField(null=True, verbose_name='Четверг - начало'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='tuesday_end',
            field=models.TimeField(null=True, verbose_name='Вторник - конец'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='tuesday_start',
            field=models.TimeField(null=True, verbose_name='Вторник - начало'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='wednesday_end',
            field=models.TimeField(null=True, verbose_name='Среда - конец'),
        ),
        migrations.AddField(
            model_name='work_time',
            name='wednesday_start',
            field=models.TimeField(null=True, verbose_name='Среда - начало'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='corps_number',
            field=models.PositiveIntegerField(max_length=1),
        ),
    ]
