# Generated by Django 3.1.7 on 2021-03-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210311_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_time',
            name='corps_number',
            field=models.PositiveIntegerField(),
        ),
    ]
