# Generated by Django 3.1.7 on 2021-03-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210311_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_time',
            name='friday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Пятница - конец'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='friday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Пятница - начало'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='monday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Понедельник - конец'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='monday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Понедельник - начало'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Суббота - конец'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Суббота - начало'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Четверг - конец'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Четверг - начало'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Вторник - конец'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Вторник - начало'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Среда - конец'),
        ),
        migrations.AlterField(
            model_name='work_time',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Среда - начало'),
        ),
    ]
